config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
               sessions: 'users/sessions',
               passwords: 'users/passwords'
                   }

  get 'admin' => 'admin#index'
  namespace :admin do
    resources :users, except: [:show]
    resources :branches, excepot: [:show] do
      scope module: :branches do
        resources :views, only: [:index, :create, :update, :destroy]
      end
    end

    namespace :clients do
      resources :phones , only: [:new, :destroy]
    end
    resources :clients do
      scope module: :clients do
        resources :orders
        resources :recipes
      end
    end

    resource :sms_mailing

    resources :products do
      scope module: :products do
        resources :views, only: [:index, :create, :update, :destroy]
      end
    end

    resources :posts, except: [:show]
    resources :grams, except: [:show]

    resources :articles do
      scope module: :articles do
        resources :blocks, only: [:create, :update, :destroy]
      end
    end

    resources :notifications
    resources :user_notifications, only: [:update]

  end

  resources :products, only: [:index, :show]
  resources :grams, only: [:index, :show]
  resources :posts, only: [:index]
  resources :articles, only: [:index, :show]

  resources :contacts, only: [:index, :show]

  post 'sms/callback' => 'sms#callback'

  get 'service' => 'welcome#service'

  get 'reviews' => 'welcome#reviews'

  get 'acuvue' => "welcome#acuvue"

  %w( 404 422 500 503).each do |code|
    get code, to: 'exceptions#show', code: code
  end

  constraints subdomain: 'mail' do
    get '/' => 'mail#index'
  end

  root to: 'welcome#index'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @recent_grams = Gram.order(created_at: :desc).limit(3)
    @breaking_news = Post.all.order(created_at: :desc).limit(4)
    @featured_products = Product.featured.limit(4)
    @recent_articles = Article.published.order(published_at: :desc).limit(3)

    @default_title = 'Оптика Стиль Новосибирск'
    @titles_list = ['Официальный сайт сети салонов']
    @meta_description = <<EOS
Мы помогаем людям видеть лучше. В стильной оправе вы будете выглядеть ярко и
модно. А в мякгих контактных линзах вы забудете о проблемах со зрением.
Далее...
EOS

  end

  def service
    @titles_list += ['Услуги']
  end

  def reviews
    @titles_list += ['Отзывы']
  end

  def acuvue
    @titles_list += ['Acuvue']
  end

end

app/views/welcome/_flamp_reviews.html.slim
.container
  .row
    .col-xs-12
      a(class="flamp-widget"
        href="https://novosibirsk.flamp.ru/firm/optika_stil_set_salonov_optiki-141265770809876"
        data-flamp-widget-type="responsive-new"
        data-flamp-widget-count="#{local_assigns[:count] || 3}"
        data-flamp-widget-id="141265770809876" data-flamp-widget-width="100%")
        ' Отзывы о нас на Флампе
      javascript:
        !function(d,s){
          var js,fjs=d.getElementsByTagName(s)[0];
          js=d.createElement(s);
          js.async=1;
          js.src="//widget.flamp.ru/loader.js";
          fjs.parentNode.insertBefore(js,fjs);
        }(document,"script");

app/views/welcome/acuvue.html.slim
.container.vertical-margin-lg
  .row
    .col-xs-10.col-xs-offset-1
      = link_to "https://www.acuvue.ru/" do
        = image_pack_tag 'acuvue_card_1.jpg', class: 'img-responsive full-width'
        = image_pack_tag 'acuvue_card_2.jpg', class: 'img-responsive full-width'

app/views/welcome/index.html.slim
= render 'layouts/slider'

.container
  .row.main-header
    .col-xs-12.col-sm-3
      h2
        b Что мы делаем лучше всего!

    .col-xs-12.col-sm-9
      p
        ' Мы помогаем людям с проблемами зрения видеть лучше. В стильной оправе вы будете выглядеть
        ' ярко, модно и привлекательно. А правильно подобранные контактные линзы позволят вам
        ' забыть, что со зрением какие-то проблемы.

  .row
    .col-sm-4
      .container-fluid
        .row
          .col-xs-2
            h3.pictogram
              b.ionicons.ion-ios-glasses
          .col-xs-10
            h2
              ' Оправы и солнцезащитные очки
              small мужские, женские, детские
            p
              small
                ' Эксклюзивные коллекции оправ и солнцезащитных очков: Roberto Cavalli, Alviero
                ' Martini, Bvlgari, Emilio Pucci, Guess, D. Swarovski, Porshe, Braccialini,
                ' Tommy Hilfiger, G. Armani, Jaguar, Silhouette, C. Paciotti, Ray Ban.

    .col-sm-4
      .container-fluid
        .row
          .col-xs-2
            h3
              = fa_icon 'wpexplorer 2x'
          .col-xs-10
            h2 Коррегирующие линзы
            p
              small
                ' Высокоиндексные, астигматические, поликарбонатные, прогрессивные, тонированные,
                ' для работы за компьютером, для вождения автомобиля, для спортивных очков,
                ' фотохромные.


    .col-sm-4
      .container-fluid
        .row
          .col-xs-2
            h3
              = fa_icon 'dot-circle-o 2x'
          .col-xs-10
            h2 Мягкие контактные линзы
            p
              small
                ' В том числе мягкие контактные линзы нового поколения ("дышащие"), а так же цветные,
                ' однодневные и линзы для коррекции астигматизма.

  .row
    .col-sm-4
      .container-fluid
        .row
          .col-xs-2
            h3
              = fa_icon 'archive 2x'
          .col-xs-10
            h2 Большой выбор сопутствующих товаров
            p
              small
                ' Большой выбор аксессуаров для очков и средств по уходу за мягкими контактными
                ' линзами.

    .col-sm-4
      .container-fluid
        .row
          .col-xs-2
            h3
              = fa_icon 'user-md 2x'
          .col-xs-10
            h2 Проверка зрения
            p
              small
                ' Опытный врач-офтальмолог поможет подборать очки и контактные линзы,
                ' даст консультацию по ношению контактных линз.
                ' Врач работает индивидуально с каждым клиентом.

    .col-sm-4
      .container-fluid
        .row
          .col-xs-2
            h3
              = fa_icon 'wrench 2x'
          .col-xs-10
            h2 Изготовление и ремонт очков
            p
              small
                ' Технологичное и тончайшее оборудование и современные
                ' расходные материалы помогают техникам по индивидуальному рецепту изготовить
                ' очки любой сложности.
hr
.container.vertical-margin-lg
  .row
    .col-xs-12.text-center
      h2 Умчи в лето с ACUVUE!
      p
        = link_to "/acuvue" do
          = image_pack_tag "Acuvue_banner_autumn.jpg", class: "img-responsive full-width"
.container-fluid.parallax
  .fader
    .container
      .row
        .col-xs-12.col-xs-offset-0.col-sm-8.col-sm-offset-2.text-center
          h2 Комфорт во всем
          p
            ' Правильно подберите очки и контактные линзы, и Вы забудете о малейшем дискомфорте.
            ' Опытные врачи-офтальмологи помогут справиться с данной задачей.
            ' А техники высокой квалификации изготовят для Вас очки. Мы гарантируем качество.
          br
          b= link_to fa_icon('long-arrow-right', right: true, text: 'Все услуги'), service_path,
                    class: 'btn btn-default btn-reverse'

- if @recent_grams.count > 0
  .container.vertical-margin-lg
    .row
      .col-xs-12
        h2
          ' Мы знаем, ЧТО вы видите
          small Фотогрфии наших клиентов в оправах

        br

    .row.gallery
      - @recent_grams.each do |gram|
        .col-xs-4.gallery-item
          = render gram if gram.present?

    row
      .col-xs-12.text-right
        b= link_to fa_icon('long-arrow-right', text: 'Все Фото клиентов', right: true), grams_path,
                  class: 'btn btn-lg'

  hr

/ .container.vertical-margin-lg
/   .row
/     .col-xs-12
/       h2 Последние новости
/       br

/   - @breaking_news.in_groups_of(2) do |group|
/     .row
/       - group.each do |post|
/         .col-xs-12.col-sm-6
/           = render partial: 'posts/post', object: post if post.present?
/   .row
/     .col-xs-12.text-right
/       b= link_to fa_icon('long-arrow-right', text: 'Все Новости', right: true), posts_path,
/                 class: 'btn btn-lg'

- if @featured_products.size > 0
  .container-fluid.bg-light-primary
    .container.vertical-margin-lg
      .row
        .col-xs-12
          h2 Каталог товаров
          br

      .visible-xs
        - @featured_products.in_groups_of(2) do |group|
          .row.gallery
            - group.each do |product|
              .col-xs-6.gallery-item.text-center
                = render product if product.present?

      .row.gallery.hidden-xs
        - @featured_products.each do |product|
          .col-xs-12.col-sm-3.gallery-item.text-center
            = render product if product.present?
      .row
        .col-xs-12.text-right
          b= link_to fa_icon('long-arrow-right', text: 'Все товары', right: true), products_path,
                    class: 'btn btn-lg'


- if @recent_articles.length > 0
  .container.vertical-margin-lg
    .row
      .col-xs-12
        h2 Полезная информация
        br

    .row.gallery
      - @recent_articles.each do |article|
        .col-sm-4.col-xs-12.gallery-item
          = render article if article.present?

    .row.col-xs-12.text-right
      b= link_to fa_icon('long-arrow-right', text: 'Другие статьи', right: true), articles_path,
                class: 'btn btn-lg'

/hr
/
/= render 'flamp_reviews', count: 3

app/views/welcome/reviews.html.slim
= render 'layouts/header', links: {current: 'Отзывы'}

= render 'flamp_reviews', count: 10

app/views/welcome/service.html.slim
= render 'layouts/header', links: {current: 'Наши услуги'}

.container-fluid
  .row
    .col-xs-12.col-xs-offset-0.col-sm-8.col-sm-offset-2.text-center
      h2 С нами удобно
      p
        ' Мы оказываем полный спектр услуг по диагностике зрения, подбору очков
        ' и контактных линз. Мы изготовим для Вас очки любой сложности по
        ' вашему индивидуальному рецепту.
      br

  .row.vertical-align-row.bg-light-primary
    .col-xs-12.col-sm-6.col-no-padding
      .container-fluid
        .row
          .col-xs-12.col-xs-offset-0.col-sm-9.col-sm-offset-1
            h2 Измерение внутриглазного давления
            p
              ' В медицинском кабинете
              = link_to "на Станиславского,16", "/contacts/stanislavskogo-16"
              '
              ' проводится
              ' измерение внутриглазного давления бесконтактным способом тонометром
              ' Keeler Pulsair (Великобритания).
              br
              br
              ' Это современный метод диагностики повышенного внутриглазного
              ' давления, который рекомендуется всем людям после 40 лет (хотя бы раз в
              ' год), особенно при глаукоме, нарушении эндокринной системы или в тканях
              ' глаза, при заболевании сосудов.
              br
              br
              ' Данная процедура очень быстрая (длится несколько секунд),
              ' безболезненная и при этом отсутствует риск инфицирования глаза.

    .col-xs-12.col-sm-6.col-no-padding
      = image_tag 'tonom-1.jpg', class: 'img-responsive full-width'

  .row.vertical-align-row.bg-light-primary
    .col-xs-12.col-sm-6.col-no-padding
      = image_tag 'cabinet-1.JPG', class: 'img-responsive full-width'

    .col-xs-12.col-sm-6.col-no-padding
      .container-fluid
        .row
          .col-xs-12.col-xs-offset-0.col-sm-9.col-sm-offset-1
            h2 Консультация офтальмолога
            p
              ' В полностью оборудованном кабинете ведет прием врач-офтальмолог, который оказывает
              ' услуги по подбору очков любой сложности, мягких контактных линз,
              ' в т.ч. для коррекции астигматизма.

  .row.vertical-align-row.bg-light-primary
    .col-xs-12.col-sm-6.col-no-padding.visible-xs
      = image_tag 'cabinet-2.jpg', class: 'img-responsive'

    .col-xs-12.col-sm-6.col-no-padding
      .container-fluid
        .row
          .col-xs-12.col-sm-9.col-xs-offset-0.col-sm-offset-1
            h2 Примерка мягких контактных линз
            p
              ' При ношении МКЛ необходимо наблюдаться у доктора, проходить осмотр не реже
              ' 1 раза в 3 месяца, желательно в одном кабинете, где вас знают и могут отследить
              ' динамику ношения контакктных линз. Также необходимо проконсультироваться по
              ' вопросам ухода за МКЛ и уточнить те симптомы, при которых обязательно нужно
              ' обратиться к доктору (рези в глазах, покраснения, светобоязнь, боль при
              ' надевании линз и др.).

    .col-xs-12.col-sm-6.col-no-padding.hidden-xs
      = image_tag 'cabinet-2.jpg', class: 'img-responsive'

  .row.vertical-align-row.bg-light-primary
    .col-xs-12.col-sm-6.col-no-padding
      = image_tag 'cabinet-3.jpg', class: 'img-responsive'

    .col-xs-12.col-sm-6.col-no-padding
      .container-fluid
        .row
          .col-xs-12.col-xs-offset-0.col-sm-9.col-sm-offset-1
            h2 Коррекция астигматизма
            p
              ' Современные мягкие контактные линзы дают новые возможности для коррекции
              ' астигматизма довольно высоких степеней, появились и контактные линзы для
              ' коррекции возрастного изменения зрения.