config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
               sessions: 'users/sessions',
               passwords: 'users/passwords'
                   }

  get 'admin' => 'admin#index'
  namespace :admin do
    resources :users, except: [:show]
    resources :branches, excepot: [:show] do
      scope module: :branches do
        resources :views, only: [:index, :create, :update, :destroy]
      end
    end

    namespace :clients do
      resources :phones , only: [:new, :destroy]
    end
    resources :clients do
      scope module: :clients do
        resources :orders
        resources :recipes
      end
    end

    resource :sms_mailing

    resources :products do
      scope module: :products do
        resources :views, only: [:index, :create, :update, :destroy]
      end
    end

    resources :posts, except: [:show]
    resources :grams, except: [:show]

    resources :articles do
      scope module: :articles do
        resources :blocks, only: [:create, :update, :destroy]
      end
    end

    resources :notifications
    resources :user_notifications, only: [:update]

  end

  resources :products, only: [:index, :show]
  resources :grams, only: [:index, :show]
  resources :posts, only: [:index]
  resources :articles, only: [:index, :show]

  resources :contacts, only: [:index, :show]

  post 'sms/callback' => 'sms#callback'

  get 'service' => 'welcome#service'

  get 'reviews' => 'welcome#reviews'

  get 'acuvue' => "welcome#acuvue"

  %w( 404 422 500 503).each do |code|
    get code, to: 'exceptions#show', code: code
  end

  constraints subdomain: 'mail' do
    get '/' => 'mail#index'
  end

  root to: 'welcome#index'
end

app/models/client.rb
class Client < ApplicationRecord

  include PgSearch

  pg_search_scope :search,
                  against: [:first_name, :last_name],
                  using: {
                      tsearch: {
                          prefix: true,
                          tsvector_column: 'tsv',
                      }
                  }

  belongs_to :branch
  has_many :orders, dependent: :destroy
  has_many :recipes, dependent: :destroy
  has_many :phones, dependent: :destroy
  has_many :smss, through: :phones
  accepts_nested_attributes_for :phones, allow_destroy: true

  validates_presence_of :last_name
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, allow_blank: true

  def full_name
    "#{last_name} #{first_name} #{patronymic}"
  end

  def last_name_initials
    "#{last_name} #{first_name.first}.#{patronymic.first}."
  end

  def age
    birth_date.present? ? ((Date.today - birth_date) / 365).floor : nil
  end


end

app/models/client/phone.rb
class Client::Phone < ApplicationRecord

  belongs_to :client
  has_many :smss, class_name: 'Client::Sms', foreign_key: 'client_phone_id'

  validates_format_of :number, with: /\A\+\d \(\d\d\d\) \d\d\d\-\d\d\-\d\d\z/,
                      message: 'должен иметь вид +7 (XXX) XXX-XX-XX',
                      allow_blank: true

  def smsable?
    if digitized_number[1].to_i == 9
      true
    else
      false
    end
  end

  def digitized_number
    number.tr('^0-9', '')
  end

end

app/models/client/sms.rb
class Client::Sms < ApplicationRecord
  class Error < StandardError; end

  belongs_to :phone, class_name: 'Client::Phone', foreign_key: 'client_phone_id'

  validates_presence_of :text
  validate :smsable_phone

  after_create :send_off

  def smsable_phone
    unless phone.smsable?
      errors.add(:phone_format, "Невозможно отправить СМС на этот номер #{phone.number}.")
    end
  end

  def send_off
    number = phone.digitized_number

    response = SmsSender.send(to: number, text: text)

    data = response['sms'][number]
    update({
               status: data['status_code'],
               sms_id: data['sms_id'],
               status_text: data.fetch('status_text', "Сообщение принято в обработку.")
           })
  end

  def reload_status
    response = SmsSender.status [sms_id]
    data = response['sms'][sms_id]
    update({
               status: data['status_code'],
               status_text: data['status_text']
           })
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :client
end

app/controllers/admin/clients/orders_controller.rb
class Admin::Clients::OrdersController < AdminController
  before_action :set_client
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /admin/clients/orders
  # GET /admin/clients/orders.json
  def index
    @orders = @client.orders
  end

  # GET /admin/clients/orders/1
  # GET /admin/clients/orders/1.json
  def show
  end

  # GET /admin/clients/orders/new
  def new
    @order = @client.orders.new
  end

  # GET /admin/clients/orders/1/edit
  def edit
  end

  # POST /admin/clients/orders
  # POST /admin/clients/orders.json
  def create
    @order = @client.orders.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to admin_client_path(@client), notice: 'Заказ создан.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/clients/orders/1
  # PATCH/PUT /admin/clients/orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to admin_client_path(@client), notice: 'Заказ сохренен.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/clients/orders/1
  # DELETE /admin/clients/orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to admin_client_path(@client, orders_page: params[:orders_page]),
                                notice: 'Заказ удален.' }
      format.json { head :no_content }
    end
  end

  private
    def set_client
      @client = Client.find(params[:client_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:id, :client_id, :number, :date, :frame, :lenses, :sum, :comment)
    end
end

app/controllers/admin/clients/phones_controller.rb
class Admin::Clients::PhonesController < AdminController
  def new

  end

  def destroy

  end
end

app/controllers/admin/clients/recipes_controller.rb
class Admin::Clients::RecipesController < AdminController
  before_action :set_client
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /admin/clients/recipes
  # GET /admin/clients/recipes.json
  def index
    @recipes = @client.recipes
  end

  # GET /admin/clients/recipes/1
  # GET /admin/clients/recipes/1.json
  def show
  end

  # GET /admin/clients/recipes/new
  def new
    @recipe = @client.recipes.new
  end

  # GET /admin/clients/recipes/1/edit
  def edit
  end

  # POST /admin/clients/recipes
  # POST /admin/clients/recipes.json
  def create
    @recipe = @client.recipes.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to admin_client_path(@client), notice: 'Рецепт создан.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/clients/recipes/1
  # PATCH/PUT /admin/clients/recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to admin_client_path(@client), notice: 'Рецепт сохранен.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/clients/recipes/1
  # DELETE /admin/clients/recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to admin_client_path(@client, recipes_page: params[:recipes_page]),
                                notice: 'Рецепт удален.' }
      format.json { head :no_content }
    end
  end

  private
    def set_client
      @client = Client.find(params[:client_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:date, :od_sph, :od_cyl, :od_ax, :od_add,
                                     :os_sph, :os_cyl, :os_ax, :os_add,
                                     :dp, :comment, :client_id)
    end
end

app/controllers/admin/clients_controller.rb
class Admin::ClientsController < AdminController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /admin/clients
  # GET /admin/clients.json
  def index
    @clients = Client.all.order(:last_name)
    @clients = @clients.where(branch_id: params[:branch]) if params[:branch].present?
    @clients = @clients.search(params[:search]) if params[:search].present?
    @clients = @clients.page(params[:page]).per_page(12)

    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /admin/clients/1
  # GET /admin/clients/1.json
  def show
    @orders = @client.orders.order(date: :desc).page(params[:orders_page]).per_page(10)
    @recipes = @client.recipes.order(date: :desc).page(params[:recipes_page]).per_page(10)
    # binding.pry
  end

  # GET /admin/clients/new
  def new
    @client = Client.new
    @client.phones.build
  end

  # GET /admin/clients/1/edit
  def edit
  end

  # POST /admin/clients
  # POST /admin/clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to admin_client_path(@client, search: params[:search], page: params[:page]),
                                  notice: 'Клиент успешно создан.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/clients/1
  # PATCH/PUT /admin/clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to admin_client_path(@client, search: params[:search], page: params[:page]),
                                  notice: 'клиент сохранен.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/clients/1
  # DELETE /admin/clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to admin_clients_url(search: params[:search], page: params[:page]),
                                notice: 'Клиент удален.' }
      format.json { head :no_content }
    end
  end

  def phone

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:first_name, :last_name, :patronymic, :email, :birth_date,
                                     :personal_data_agreement, :email_notification_agreement, :sms_notification_agreement,
                                     :branch_id, :comment,
                                     phones_attributes: [:id, :number, :comment, :_destroy])
    end
end

app/helpers/admin/clients/orders_helper.rb
module Admin::Clients::OrdersHelper
end

app/helpers/admin/clients/recipes_helper.rb
module Admin::Clients::RecipesHelper
end

app/helpers/admin/clients_helper.rb
module Admin::ClientsHelper
end

app/views/admin/clients/orders/_form.html.slim
= custom_form_for [:admin, @client, @order] do |f|
  .form-row
    .col-xs-12
      = f.label :number
      = f.text_field :number

  .form-row
    .col-xs-12
      = f.label :date
      = f.date_field :date, value: (@order.date.present? ? @order.date : Date.today)

  .form-row
    .col-xs-12
      = f.label :frame
      = f.text_field :frame

  .form-row
    .col-xs-12
      = f.label :lenses
      = f.text_field :lenses

  .form-row
    .col-xs-12
      = f.label :sum
      = f.text_field :sum


  .form-row
    .col-xs-3
      = f.label :od_sph
      = f.text_field :od_sph
    .col-xs-3
      = f.label :od_cyl
      = f.text_field :od_cyl
    .col-xs-3
      = f.label :od_ax
      = f.text_field :od_ax
    .col-xs-3
      = f.label :od_add
      = f.text_field :od_add

  .form-row
    .col-xs-3
      = f.label :os_sph
      = f.text_field :os_sph
    .col-xs-3
      = f.label :os_cyl
      = f.text_field :os_cyl
    .col-xs-3
      = f.label :os_ax
      = f.text_field :os_ax
    .col-xs-3
      = f.label :os_add
      = f.text_field :os_add

  .form-row
    .col-xs-4.col-xs-offset-4
      = f.label :dp
      = f.text_field :dp
    .col-xs-4

  .form-row
    .col-xs-12
      = f.label :comment
      = f.text_field :comment

  .form-row
    .col-xs-12
      br
      = f.submit class: 'btn btn-success'

app/views/admin/clients/orders/_order.html.slim
tr.order id=order.id
  td = order.number
  td = l order.date, format: :date
  td = order.frame
  td = order.lenses
  td = order.sum
  td
    'sph:
    b = order.od_sph
    - if order.od_cyl.present?
      '  cyl:
      b = order.od_cyl
    - if order.od_ax.present?
      '  ax:
      b = order.od_ax
    - if order.od_add.present?
      ' add:
      b = order.od_add
  td
    'sph:
    b = order.os_sph
    - if order.os_cyl.present?
      '  cyl:
      b = order.os_cyl
    - if order.os_ax.present?
      '  ax:
      b = order.os_ax
    - if order.os_add.present?
      ' add:
      b = order.os_add

  td = order.dp
  td = order.comment
  td
    = link_to fa_icon('pencil-square-o'), edit_admin_client_order_path(order.client, order), data: { toggle: 'tooltip' },
            title: 'Правка', class: 'btn btn-sm btn-default'

    = link_to fa_icon('trash-o'), admin_client_order_path(order.client, order, page: params[:orders_page]),
            method: :delete, remote: true,
            data: { confirm: "Вы действительно хотите удалить заказ <b>№#{order.number} от #{l order.date, format: :date}</b>?",
                    header: 'Подтвердите, пожалуйста.',
                    toggle: 'tooltip' },
            title: 'Удалить',
            class: 'btn btn-sm btn-default'

app/views/admin/clients/orders/_pagination.html.slim
.row
  .col-xs-8
    = will_paginate @orders, renderer: BootstrapPagination::Rails,
            inner_window: 3, outer_window: 0, param_name: :orders_page
  .col-xs-4.text-right
    ul.pagination
      li = link_to fa_icon('plus', text: 'Добавить заказ'), new_admin_client_order_path(@client)

- if @orders.size > 0
  table.table.table-condensed.table-responsive
    thead
      tr
        th №
        th Дата
        th Оправа / Цена
        th Линзы / Цена
        th Сумма заказа
        th OD
        th OS
        th DP
        th комментарии
        th
    tbody = render partial: 'admin/clients/orders/order', collection: @orders

- else
  br
  ' Пока заказов нет. Хотите добавить?

= will_paginate @orders, renderer: BootstrapPagination::Rails,
        inner_window: 3, outer_window: 0, param_name: :orders_page

app/views/admin/clients/orders/edit.html.slim
.container
  .row
    .col-xs-12
      h1 Правка заказ для #{@order.client.full_name}
      = render 'form'

  .row
    .col-xs-12
      br
      = link_to 'Назад', admin_client_path(@order.client)

app/views/admin/clients/orders/index.html.slim
.container
  .row
    .col-xs-12
      h1 Заказы

  .row
    = render 'pagination'

app/views/admin/clients/orders/new.html.slim
.container
  .row
    .col-xs-12
      h1 Новый заказ для #{@order.client.full_name}
      = render 'form'

  .row
    .col-xs-12
      br
      = link_to 'Назад', admin_client_path(@order.client)

app/views/admin/clients/orders/show.html.slim
p#notice = notice


= link_to 'Edit', edit_admin_clients_order_path(@order)
'  |
= link_to 'Back', admin_clients_orders_path